// Autogenerated by typings-for-css-modules-loader.
// Please do not modify this file !

declare namespace LoginSceneModuleCssNamespace {
  export interface ILoginSceneModuleCss {
    home: string;
  }
}

declare const LoginSceneModuleCssModule: LoginSceneModuleCssNamespace.ILoginSceneModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LoginSceneModuleCssNamespace.ILoginSceneModuleCss;
};

export = LoginSceneModuleCssModule;
