name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --no-frozen-lockfile

  project-lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-pnpm
      - uses: ./.github/actions/setup-nx-cache
      - name: Install dependencies
        run: pnpm install
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm exec nx workspace-lint
      - run: pnpm exec nx format:check

  nx-task:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        target: ['lint', 'test', 'build']
        jobIndex: [1, 2, 3, 4] # this will needs to be changed regarding the number of projects
    env:
      JOB_COUNT: 4 # must be changed too, correspond to the jobIndex array length
      NX_VERBOSE_LOGGING: true
      NX_E2E_SKIP_BUILD_CLEANUP: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - uses: nrwl/nx-set-shas@v3
      - run: git config --global user.email "test@test.com"
      - run: git config --global user.name "Test"
      - name: run-many
        run: pnpm run run-many ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.JOB_COUNT }} $GITHUB_REF
